
#### DEPLOYMENT ###

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: projektwarehouseapp
  name: warehouseapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouseapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: warehouseapp
    spec:
      containers:
      - command:
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/walletapp:2.0
        name: warehouseapp
        resources: {}
        ports:
        - containerPort: 3000
status: {}

---

#### SERVICE ###

apiVersion: v1
kind: Service
metadata:
  name: projektwarehouseappsvc
  labels:
    app: projektwarehouseapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: warehouseapp
  type: ClusterIP

---

#### ROUTE ###

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: projektwarehouseapp
  name: warehouserte
spec:
  host: ""
  port:
    targetPort: 3000
  to:
    kind: Service
    name: projektshopappsvc
    weight: 100